import type { ConceptPreset } from "./types";

/** 6. 핵심 소재 및 공간 — 다중 선택 태그 (맥락 필터 적용) */
export const TROPE_PRESETS: ConceptPreset[] = [
  // 주요 무대/공간
  {
    id: "academy",
    label: "#아카데미",
    description: "학교·마탑·기사단 학원.",
    group: "공간/무대 특화",
    affinity: { tags: ["fantasy", "romance", "modern", "male", "female"] },
    rules: "학원·등급·시험·라이벌 구조. 캠퍼스/학원 묘사 일관.",
  },
  {
    id: "tower",
    label: "#탑등반",
    description: "무한 경쟁 탑.",
    group: "공간/무대 특화",
    affinity: { tags: ["game", "hunter", "fantasy", "male", "system"] },
    rules: "층·보상·경쟁·사망 규칙 명확. 등반 긴장 유지.",
  },
  {
    id: "dungeon-gate",
    label: "#던전/게이트",
    description: "던전·게이트 공략.",
    group: "공간/무대 특화",
    affinity: { tags: ["hunter", "game", "fantasy", "modern", "male", "system"] },
    rules: "던전 규칙·몬스터·드롭. 파티·공략 전술.",
  },
  {
    id: "territory",
    label: "#영지경영",
    description: "영지·영주 경영.",
    group: "공간/무대 특화",
    affinity: { tags: ["fantasy", "historical", "male", "female"] },
    rules: "영지 자원·민심·건설·외적 위협.",
  },
  {
    id: "court",
    label: "#황궁/사교계",
    description: "궁중·귀족 사교.",
    group: "공간/무대 특화",
    affinity: { tags: ["historical", "fantasy", "romance", "female", "oriental"] },
    rules: "예법·암투·연회·신분 차이.",
  },
  {
    id: "entertainment",
    label: "#연예계/방송국",
    description: "연예·방송 무대.",
    group: "공간/무대 특화",
    affinity: { tags: ["modern", "romance", "female", "male"] },
    rules: "방송·스캔들·인기·계약 구조.",
  },
  {
    id: "chaebol",
    label: "#기업/재벌가",
    description: "재벌·기업 정치.",
    group: "공간/무대 특화",
    affinity: { tags: ["modern", "romance", "male", "female"] },
    rules: "지분·승계·인수·오피스 정치.",
  },
  {
    id: "military",
    label: "#군부대",
    description: "군대·전쟁 무대.",
    group: "공간/무대 특화",
    affinity: { tags: ["historical", "modern", "male", "sf"] },
    rules: "계급·규율·작전·전우애.",
  },
  {
    id: "campus",
    label: "#캠퍼스",
    description: "대학·고등학교.",
    group: "공간/무대 특화",
    affinity: { tags: ["modern", "romance", "female", "male"] },
    rules: "학교 생활·동아리·시험·청춘.",
  },
  {
    id: "office",
    label: "#오피스",
    description: "직장·사무실.",
    group: "공간/무대 특화",
    affinity: { tags: ["modern", "romance", "female"] },
    rules: "직장 정치·프로젝트·동료 관계.",
  },
  // 주인공 포지션/신분
  {
    id: "delinquent",
    label: "#망나니",
    description: "문제아·불량 주인공.",
    group: "주인공 포지션/신분",
    affinity: { tags: ["male", "modern", "wuxia"] },
    rules: "반항·성장·의외의 면모. 과도한 폭력 지양(이용등급 준수).",
  },
  {
    id: "terminal",
    label: "#시한부",
    description: "시한부 설정.",
    group: "주인공 포지션/신분",
    affinity: { tags: ["romance", "modern", "female", "male"] },
    rules: "시간 압박·선택의 무게. 감정선 깊게.",
  },
  {
    id: "villainess",
    label: "#악녀",
    description: "악역 여주·파멸 회피.",
    group: "주인공 포지션/신분",
    affinity: { tags: ["female", "romance", "fantasy", "historical"] },
    rules: "원작·운명 압박. 선택이 원작과 어긋날 때 긴장.",
  },
  {
    id: "tyrant",
    label: "#폭군",
    description: "폭군 회피·개혁.",
    group: "주인공 포지션/신분",
    affinity: { tags: ["romance", "fantasy", "historical", "female", "oriental"] },
    rules: "권력·공포·개혁 동기. 신하·백성 반응.",
  },
  {
    id: "necromancer",
    label: "#네크로맨서",
    description: "언데드·사령.",
    group: "주인공 포지션/신분",
    affinity: { tags: ["fantasy", "male", "game", "horror"] },
    rules: "사령 규칙·윤리·사회적 시선.",
  },
  {
    id: "saint",
    label: "#성녀/성기사",
    description: "성녀·성기사 신분.",
    group: "주인공 포지션/신분",
    affinity: { tags: ["fantasy", "romance", "female", "historical"] },
    rules: "신앙·기적·정치적 이용.",
  },
  {
    id: "rich-heir",
    label: "#재벌3세",
    description: "재벌·금수저.",
    group: "주인공 포지션/신분",
    affinity: { tags: ["modern", "romance", "male", "female"] },
    rules: "자원·권력·가문 기대와 부담.",
  },
  {
    id: "overpowered",
    label: "#먼치킨",
    description: "절대적 강자.",
    group: "주인공 포지션/신분",
    rules: "압도적 힘에도 갈등·목표 필요. 긴장은 관계·선택에서.",
  },
  {
    id: "genius",
    label: "#천재",
    description: "천재성·재능.",
    group: "주인공 포지션/신분",
    rules: "재능 발휘는 행동으로. 설명조 지식 나열 지양.",
  },
  {
    id: "craftsman",
    label: "#장인",
    description: "대장·요리 등 장인.",
    group: "주인공 포지션/신분",
    affinity: { tags: ["fantasy", "modern", "male"] },
    rules: "기술·성장·의뢰·명성 구조.",
  },
  {
    id: "mastermind",
    label: "#흑막",
    description: "뒤에서 조종.",
    group: "주인공 포지션/신분",
    affinity: { tags: ["fantasy", "historical", "male", "romance"] },
    rules: "정보·계획·대리인. 정체 노출 타이밍.",
  },
  {
    id: "nonhuman",
    label: "#인외존재",
    description: "슬라임 등 비인간.",
    group: "주인공 포지션/신분",
    affinity: { tags: ["fantasy", "game", "male"] },
    rules: "종족 특성·진화·인간 사회와의 관계.",
  },
  // 인물 관계 및 로맨스
  {
    id: "enemies-to-lovers",
    label: "#혐관",
    description: "혐오에서 시작하는 관계.",
    group: "공용/관계성 특화",
    affinity: { tags: ["romance", "female", "male", "bl", "gl"] },
    rules: "감정 변화 단계적·설득력 있게.",
  },
  {
    id: "pure-love",
    label: "#순애",
    description: "순수한 사랑.",
    group: "공용/관계성 특화",
    affinity: { tags: ["romance", "female", "bl", "gl"] },
    rules: "진심·오해·보호 본능. 과도한 집착은 톤에 맞게.",
  },
  {
    id: "obsession",
    label: "#집착/광기",
    description: "집착·광기 로맨스.",
    group: "공용/관계성 특화",
    affinity: { tags: ["romance", "female", "bl", "gl", "horror"] },
    rules: "심리·경계·긴장. 이용등급 준수.",
  },
  {
    id: "contract-romance",
    label: "#계약관계",
    description: "계약 결혼·연애.",
    group: "공용/관계성 특화",
    affinity: { tags: ["romance", "modern", "female"] },
    rules: "계약 조건·감정 변화·해지 위기.",
  },
  {
    id: "regret-romance",
    label: "#후회물",
    description: "후회하는 전 연인.",
    group: "공용/관계성 특화",
    affinity: { tags: ["romance", "female", "modern", "fantasy"] },
    rules: "과거 선택·후회·재회 긴장.",
  },
  {
    id: "misunderstanding",
    label: "#착각계",
    description: "오해·착각·찬양.",
    group: "공용/관계성 특화",
    affinity: { tags: ["romance", "fantasy", "modern", "female", "male"] },
    rules: "착각 코미디·오해 해소 타이밍.",
  },
  {
    id: "revenge",
    label: "#사이다/복수극",
    description: "복수·사이다.",
    group: "공용/관계성 특화",
    affinity: { tags: ["male", "female", "fantasy", "modern", "romance"] },
    rules: "억울함·복선·통쾌한 응징. 과도한 잔혹 지양.",
  },
  {
    id: "family-regret",
    label: "#가족후회물",
    description: "가족의 후회·화해.",
    group: "공용/관계성 특화",
    affinity: { tags: ["romance", "fantasy", "modern", "female"] },
    rules: "가족 갈등·과거·용서 아크.",
  },
  {
    id: "parenting",
    label: "#육아물",
    description: "육아·양육.",
    group: "공용/관계성 특화",
    affinity: { tags: ["romance", "fantasy", "modern", "female"] },
    rules: "아이 성장·부모 감정·일상 warmth.",
  },
  {
    id: "harem",
    label: "#하렘/역하렘",
    description: "다수 연애 대상.",
    group: "공용/관계성 특화",
    affinity: { tags: ["romance", "male", "female", "fantasy", "modern"] },
    rules: "인물별 차별화·감정선·독자 기대 관리.",
  },
  {
    id: "redemption",
    label: "#구원서사",
    description: "구원·치유.",
    group: "공용/관계성 특화",
    affinity: { tags: ["romance", "bl", "gl", "fantasy", "modern"] },
    rules: "트라우마·신뢰·회복 과정.",
  },
  {
    id: "carry",
    label: "#캐리물",
    description: "주인공이 타인을 끌어올림.",
    group: "공용/관계성 특화",
    affinity: { tags: ["game", "male", "hunter", "fantasy"] },
    rules: "멘토·보호·성장 지원. 피캐리 과몰입 지양.",
  },
  // 특수/트렌드
  {
    id: "streaming",
    label: "#인터넷방송",
    description: "스트리머·방송.",
    group: "장르별 특화 소재",
    affinity: { tags: ["modern", "game", "male", "system"] },
    rules: "채팅·시청자·바이럴·논란.",
  },
  {
    id: "professional",
    label: "#전문직",
    description: "의사·판검사 등.",
    group: "장르별 특화 소재",
    affinity: { tags: ["modern", "romance", "female", "male"] },
    rules: "직업 전문성·윤리·사건 연계.",
  },
  {
    id: "sports",
    label: "#스포츠",
    description: "야구·축구 등.",
    group: "장르별 특화 소재",
    affinity: { tags: ["modern", "male"] },
    rules: "경기·팀·성장·부상·승부.",
  },
  {
    id: "alt-history-tech",
    label: "#대체역사",
    description: "국뽕·기술발전.",
    group: "장르별 특화 소재",
    affinity: { tags: ["historical", "male", "oriental"] },
    rules: "기술 전파·정치·역사 인과.",
  },
  {
    id: "hunter",
    label: "#헌터물",
    description: "헌터·게이트.",
    group: "장르별 특화 소재",
    affinity: { tags: ["hunter", "modern", "male", "game", "system"] },
    rules: "등급·길드·레이드·사냥 규칙.",
  },
  {
    id: "idol-actor",
    label: "#아이돌/배우",
    description: "연예인 신분.",
    group: "장르별 특화 소재",
    affinity: { tags: ["modern", "romance", "female"] },
    rules: "스케줄·팬·스캔들·작품 활동.",
  },
  {
    id: "urban-legend",
    label: "#괴담/나폴리탄",
    description: "괴담·호러 일상.",
    group: "장르별 특화 소재",
    affinity: { tags: ["horror", "modern"] },
    rules: "불길·규칙 괴담·공포 암시.",
  },
  {
    id: "true-madness",
    label: "#진짜광기",
    description: "극단적 광기.",
    group: "장르별 특화 소재",
    affinity: { tags: ["horror", "male", "modern"] },
    rules: "예측 불가·상식 파괴. 톤과 이용등급 준수.",
  },
  {
    id: "orthodox-sect",
    label: "#구파일방",
    description: "정파 무림 세력.",
    group: "장르별 특화 소재",
    affinity: { tags: ["wuxia", "oriental"] },
    rules: "구파 일원·의리·문파 규율. 정사 대립 구조.",
  },
  {
    id: "demon-sect",
    label: "#마교",
    description: "마교·사파 세력.",
    group: "장르별 특화 소재",
    affinity: { tags: ["wuxia", "oriental"] },
    rules: "사파 규칙·공포·권력. 정파와 대립.",
  },
  {
    id: "heavenly-demon",
    label: "#천마",
    description: "천마·마도 거한.",
    group: "장르별 특화 소재",
    affinity: { tags: ["wuxia", "oriental", "male"] },
    rules: "천마 신화·무림 격변. 압도적 위압감.",
  },
];

export function getTropeById(id: string): ConceptPreset | undefined {
  return TROPE_PRESETS.find((p) => p.id === id);
}

export function tropeGroups(): string[] {
  return [...new Set(TROPE_PRESETS.map((p) => p.group!).filter(Boolean))];
}

export function filteredTropeGroups(
  presets: ConceptPreset[]
): string[] {
  return [...new Set(presets.map((p) => p.group!).filter(Boolean))];
}
